export const plans_fr = [
  {
    title: "Starter",
    caracts: [
      { label: "Les format court tels que Tiktok/reels/shorts", available: true },
      { label: "8000 mots par mois", available: true },
      { label: "jusqu'a 5 utilisateurs", available: true },
      { label: "24+ langues", available: true },
      { label: "Anti-plagiat", available: true },
      { label: "Grammaire parfaite", available: true },
      { label: "Support client", available: true },
      { label: "Format Long", available: false },
      { label: "Qualité de mots premium", available: false },
      { label: "Description optimisé", available: false },
    ],
    price: "$19,99",
    type: "starter",
  },
  {
    title: "Premium",
    caracts: [
      { label: "Les format court tels que Tiktok/reels/shorts", available: true },
      { label: "20000 mots par mois", available: true },
      { label: "jusqu'a 5 utilisateurs", available: true },
      { label: "24+ langues", available: true },
      { label: "Anti-plagiat", available: true },
      { label: "Grammaire parfaite", available: true },
      { label: "Support client", available: true },
      { label: "Format Long", available: true },
      { label: "Qualité de mots premium", available: true },
      { label: "Description optimisé", available: true },
    ],
    price: "$39,99",
    type: "premium",
  },
  {
    title: "custom",
    caracts: [
      { label: "Les format court tels que Tiktok/reels/shorts", available: true },
      { label: "+50000 mots par mois", available: true },
      { label: "jusqu'a 5 utilisateurs", available: true },
      { label: "24+ langues", available: true },
      { label: "Anti-plagiat", available: true },
      { label: "Grammaire parfaite", available: true },
      { label: "Support client", available: true },
      { label: "Format Long", available: true },
      { label: "Qualité de mots premium", available: true },
      { label: "Description optimisé", available: true },
    ],
    price: "+$99,99",
    type: "custom",
  },
];

export const plans_en = [
  {
    title: "Starter",
    caracts: [
      { label: "Short formats such as Tiktok/reels/shorts", available: true },
      { label: "8000 words per month", available: true },
      { label: "up to 5 users", available: true },
      { label: "24+ LANGUAGES", available: true },
      { label: "Anti-plagiarism", available: true },
      { label: "Perfect grammar", available: true },
      { label: "Customer Support", available: true },
      { label: "Long format", available: false },
      { label: "Premium word quality", available: false },
      { label: "Description optimized", available: false },
    ],
    price: "$19,99",
    type: "starter",
  },
  {
    title: "Premium",
    caracts: [
      { label: "Short formats such as Tiktok/reels/shorts", available: true },
      { label: "20000 words per month", available: true },
      { label: "up to 5 users", available: true },
      { label: "24+ LANGUAGES", available: true },
      { label: "Anti-plagiarism", available: true },
      { label: "Perfect grammar", available: true },
      { label: "Customer Support", available: true },
      { label: "Long format", available: true },
      { label: "Premium word quality", available: true },
      { label: "Description optimized", available: true },
    ],
    price: "$39,99",
    type: "premium",
  },
  {
    title: "Custom",
    caracts: [
      { label: "Short formats such as Tiktok/reels/shorts", available: true },
      { label: "+20000 words per month", available: true },
      { label: "up to 5 users", available: true },
      { label: "24+ LANGUAGES", available: true },
      { label: "Anti-plagiarism", available: true },
      { label: "Perfect grammar", available: true },
      { label: "Customer Support", available: true },
      { label: "Long format", available: true },
      { label: "Premium word quality", available: true },
      { label: "Description optimized", available: true },
    ],
    price: "+$99,99",
    type: "custom",
  },
];
